%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/humble/.*$
%global __requires_exclude_from ^/opt/ros/humble/.*$

%global __cmake_in_source_build 1

Name:           ros-humble-ur-client-library
Version:        2.7.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS ur_client_library package

License:        Apache-2.0 and BSD-2-Clause and Zlib and MIT and MIT
URL:            http://wiki.ros.org/ur_client_library
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-humble-ament-cmake
Requires:       ros-humble-ros-workspace
BuildRequires:  cmake3
BuildRequires:  ros-humble-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
Standalone C++ library for accessing Universal Robots interfaces. This has been
forked off the ur_robot_driver.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/humble" \
    -DCMAKE_PREFIX_PATH="/opt/ros/humble" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/humble/setup.sh" ]; then . "/opt/ros/humble/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
%license 3rdparty/urcl_3rdparty/httplib/LICENSE.txt
%license 3rdparty/urcl_3rdparty/nlohmann_json/LICENSE.MIT.txt
%license LICENSE_apache_2_0
%license include/ur_client_library/queue/LICENSE.md
%license include/ur_client_library/queue/atomicops.h
/opt/ros/humble

%changelog
* Fri Feb 20 2026 Felix Exner <feex@universal-robots.com> - 2.7.0-1
- Autogenerated by Bloom

* Thu Dec 04 2025 Felix Exner <feex@universal-robots.com> - 2.6.1-1
- Autogenerated by Bloom

* Tue Nov 11 2025 Felix Exner <feex@universal-robots.com> - 2.6.0-1
- Autogenerated by Bloom

* Sat Oct 25 2025 Felix Exner <feex@universal-robots.com> - 2.5.0-1
- Autogenerated by Bloom

* Mon Oct 13 2025 Felix Exner <feex@universal-robots.com> - 2.4.0-1
- Autogenerated by Bloom

* Mon Sep 15 2025 Felix Exner <feex@universal-robots.com> - 2.3.0-1
- Autogenerated by Bloom

* Mon Jul 21 2025 Felix Exner <feex@universal-robots.com> - 2.2.0-1
- Autogenerated by Bloom

* Wed Jun 18 2025 Felix Exner <feex@universal-robots.com> - 2.1.0-1
- Autogenerated by Bloom

* Wed Apr 23 2025 Felix Exner <feex@universal-robots.com> - 2.0.0-1
- Autogenerated by Bloom

* Fri Mar 28 2025 Felix Exner <feex@universal-robots.com> - 1.9.0-1
- Autogenerated by Bloom

* Mon Mar 17 2025 Felix Exner <feex@universal-robots.com> - 1.8.0-1
- Autogenerated by Bloom

* Tue Feb 25 2025 Felix Exner <feex@universal-robots.com> - 1.7.1-1
- Autogenerated by Bloom

* Thu Feb 20 2025 Felix Exner <feex@universal-robots.com> - 1.7.0-1
- Autogenerated by Bloom

* Fri Jan 24 2025 Felix Exner <feex@universal-robots.com> - 1.6.0-1
- Autogenerated by Bloom

* Mon Nov 25 2024 Felix Exner <exner@fzi.de> - 1.5.0-1
- Autogenerated by Bloom

* Wed Sep 11 2024 Felix Exner <exner@fzi.de> - 1.4.0-1
- Autogenerated by Bloom

* Mon Jun 03 2024 Felix Exner <exner@fzi.de> - 1.3.7-1
- Autogenerated by Bloom

* Mon Apr 08 2024 Felix Exner <exner@fzi.de> - 1.3.6-1
- Autogenerated by Bloom

* Thu Apr 04 2024 Felix Exner <exner@fzi.de> - 1.3.5-2
- Autogenerated by Bloom

* Sun Feb 25 2024 Felix Exner <exner@fzi.de> - 1.3.5-1
- Autogenerated by Bloom

* Mon Sep 25 2023 Felix Exner <exner@fzi.de> - 1.3.4-1
- Autogenerated by Bloom

* Wed Sep 06 2023 Felix Exner <exner@fzi.de> - 1.3.3-1
- Autogenerated by Bloom

* Thu Jul 13 2023 Felix Exner <exner@fzi.de> - 1.3.2-1
- Autogenerated by Bloom

* Wed Nov 30 2022 Felix Exner <exner@fzi.de> - 1.3.1-1
- Autogenerated by Bloom

* Tue Oct 04 2022 Felix Exner <exner@fzi.de> - 1.2.0-1
- Autogenerated by Bloom

* Tue Apr 19 2022 Felix Exner <exner@fzi.de> - 1.0.0-3
- Autogenerated by Bloom

* Wed Mar 02 2022 Felix Exner <exner@fzi.de> - 1.0.0-2
- Autogenerated by Bloom

* Thu Feb 03 2022 Felix Exner <exner@fzi.de> - 1.0.0-1
- Autogenerated by Bloom

